# Generated by Django 4.2.6 on 2024-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, unique=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('photo', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('status', models.CharField(choices=[('completed', 'Выполнен'), ('quickly', 'Срочно'), ('full', 'Набор окончен'), ('process', 'В процессе'), ('frozen', 'Заморожен')], default='process', help_text='Ведите состояние (статус) проекта. По умолчанию статус - В процессе', max_length=14, verbose_name='Статус')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updation_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('phone', models.CharField(verbose_name='Номер телефона руководителя', blank=False, max_length=14)),
                ('link', models.URLField(verbose_name='Ссылка на сайт проекта', blank=True, help_text='*необязательное поле')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
