# Generated by Django 4.2.6 on 2024-01-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0002_create_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprojects',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название подпроекта', max_length=80, unique=True, verbose_name='Название подпроекта')),
                ('description', models.TextField(help_text='Краткое описание проекта', max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updation_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('completed', 'Выполнен'), ('quickly', 'Срочно'), ('full', 'Набор окончен'), ('process', 'В процессе'), ('frozen', 'Заморожен')], default='process', help_text='Ведите состояние (статус) проекта. По умолчанию статус - В процессе', max_length=11, verbose_name='Статус')),
                ('pid', models.ForeignKey(help_text='Необходимо указать к какому проекту принадлежит', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects', verbose_name='Идентификатор проекта')),
            ],
            options={
                'verbose_name': 'Подпроект',
                'verbose_name_plural': 'Подпроекты',
            },
        ),
    ]
