# Generated by Django 4.2.6 on 2024-08-13 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0006_fix_photo_and_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, help_text='*необязательное поле, запись в формате "x,x"', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг проекта'),
        ),
    ]
