version: '3.11-slim'

services:
  django_container:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - static:/static
    image: csu_prj:latest
    container_name: django_container
    ports:
      - 8000:8000
    env_file:
      .env

  nginx_container:
    build: ./nginx
    volumes:
      - static:/static
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - django_container

volumes:
  static: