# Generated by Django 4.2.6 on 2023-11-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProjects',
            fields=[
                ('comp_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('comp_project_description', models.TextField(help_text='Краткое описание выполненного проекта', max_length=255, verbose_name='Описание')),
                ('comp_project_preview', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('comp_project_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Выполенный проект',
                'verbose_name_plural': 'Выполненные проекты',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=80, unique=True, verbose_name='Название проекта')),
                ('project_description', models.TextField(verbose_name='Краткое описание')),
                ('project_preview', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('project_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_full_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('worker_photo', models.ImageField(upload_to='peoples/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='WorkersInProject',
            fields=[
                ('w_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_post', models.CharField(max_length=80, verbose_name='Должность')),
                ('worker_description', models.TextField(help_text='Краткое описание чем занимался в проекте', max_length=255, verbose_name='Описание')),
                ('comp_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.completedprojects', verbose_name='Название проекта')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.workers', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('subproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subproject_name', models.CharField(help_text='Название подпроекта', max_length=80, unique=True, verbose_name='Название подпроекта')),
                ('subproject_description', models.TextField(help_text='Краткое описание проекта', verbose_name='Описание')),
                ('subproject_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('project_id', models.ForeignKey(help_text='Необходимо указать к какому проекту принадлежит', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects', verbose_name='Идентификатор проекта')),
            ],
            options={
                'verbose_name': 'Подпроект',
                'verbose_name_plural': 'Подпроекты',
            },
        ),
        migrations.CreateModel(
            name='SubProjectNeeds',
            fields=[
                ('need_id', models.AutoField(primary_key=True, serialize=False)),
                ('need_description', models.TextField(help_text='Краткое описание требований', max_length=255, verbose_name='Требования к работнику')),
                ('need_profiles', models.CharField(help_text='Требуемые профили обучения', max_length=80, verbose_name='Специальность')),
                ('subproject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects', verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
