# Generated by Django 4.2.6 on 2023-10-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_projects',
            fields=[
                ('comp_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_project_name', models.CharField(help_text='Название выполненного проекта', max_length=255)),
                ('comp_project_description', models.CharField(help_text='Описание выполненного проекта', max_length=255)),
                ('comp_project_preview', models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='static/src/img/compProjects/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(help_text='Название проекта', unique=True)),
                ('project_description', models.TextField(help_text='Описание проекта')),
                ('project_preview', models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='static/src/img/projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_full_name', models.CharField(max_length=127)),
                ('worker_post', models.CharField(max_length=127)),
                ('worker_description', models.TextField()),
                ('worker_photo', models.ImageField(upload_to='static/src/img/compProjects/workers/')),
                ('comp_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.completed_projects')),
            ],
        ),
        migrations.CreateModel(
            name='Subprojects',
            fields=[
                ('subproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subproject_name', models.CharField(help_text='Название подпроекта', max_length=100, unique=True)),
                ('subproject_description', models.TextField(help_text='Описание подпроекта')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject_needs',
            fields=[
                ('need_id', models.AutoField(primary_key=True, serialize=False)),
                ('need_description', models.CharField(help_text='Описание требований к студентам', max_length=255)),
                ('need_profiles', models.CharField(help_text='Требуемые профили обучения', max_length=255)),
                ('subproject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects')),
            ],
        ),
    ]
