# Generated by Django 4.2.6 on 2023-12-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=80, unique=True, verbose_name='Название проекта')),
                ('prj_description', models.TextField(verbose_name='Краткое описание')),
                ('prj_preview', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('prj_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('prj_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('prj_year_created', models.DateField(auto_now_add=True, verbose_name='Год создания')),
                ('status', models.CharField(choices=[('notComplete', 'Не выполнен'), ('partial', 'Недобор'), ('complete', 'Выполнен')], default='notComplete', help_text=' Введите статус готовности (по умолчанию статус не готов)', max_length=11, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_full_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('worker_photo', models.ImageField(upload_to='peoples/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='WorkersInProject',
            fields=[
                ('w_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_post', models.CharField(max_length=80, verbose_name='Должность')),
                ('worker_description', models.TextField(help_text='Краткое описание чем занимался в проекте', max_length=255, verbose_name='Описание')),
                ('prj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects', verbose_name='Название проекта')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.workers', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.CreateModel(
            name='SubProjects',
            fields=[
                ('subprj_id', models.AutoField(primary_key=True, serialize=False)),
                ('subprj_name', models.CharField(help_text='Название подпроекта', max_length=80, unique=True, verbose_name='Название подпроекта')),
                ('subprj_description', models.TextField(help_text='Краткое описание проекта', verbose_name='Описание')),
                ('subprj_preview', models.ImageField(blank=True, help_text='*необязательное поле', upload_to='previews/', verbose_name='Превью проекта')),
                ('subprj_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subprj_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('subprj_year', models.DateField(auto_now_add=True, verbose_name='Год создания')),
                ('status', models.CharField(choices=[('notComplete', 'Не выполнен'), ('partial', 'Недобор'), ('complete', 'Выполнен')], default='notComplete', help_text=' Введите статус готовности (по умолчанию статус не готов)', max_length=11, verbose_name='Статус')),
                ('prj_id', models.ForeignKey(help_text='Необходимо указать к какому проекту принадлежит', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects', verbose_name='Идентификатор проекта')),
            ],
            options={
                'verbose_name': 'Подпроект',
                'verbose_name_plural': 'Подпроекты',
            },
        ),
        migrations.CreateModel(
            name='SubProjectNeeds',
            fields=[
                ('need_id', models.AutoField(primary_key=True, serialize=False)),
                ('need_description', models.TextField(help_text='Краткое описание требований', max_length=255, verbose_name='Требования к работнику')),
                ('need_profiles', models.CharField(help_text='Требуемые профили обучения', max_length=80, verbose_name='Специальность')),
                ('subprj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects', verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
