# Generated by Django 4.2.6 on 2023-11-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProjects',
            fields=[
                ('comp_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_project_name', models.CharField(help_text='Название выполненного проекта', max_length=255)),
                ('comp_project_description', models.CharField(help_text='Описание выполненного проекта', max_length=255)),
                ('comp_project_preview', models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='previews/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersInProject',
            fields=[
                ('w_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_post', models.CharField(max_length=80)),
                ('worker_description', models.CharField(max_length=255)),
                ('comp_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.completedprojects')),
            ],
        ),
        migrations.RenameModel(
            old_name='Subproject_needs',
            new_name='SubProjectNeeds',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='comp_project_id',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='worker_description',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='worker_post',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_preview',
            field=models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='previews/'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='worker_full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='worker_photo',
            field=models.ImageField(upload_to='peoples/'),
        ),
        migrations.DeleteModel(
            name='Completed_projects',
        ),
        migrations.AddField(
            model_name='workersinproject',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.workers'),
        ),
    ]
