# Generated by Django 4.2.6 on 2023-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_projects',
            name='comp_project_preview',
            field=models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='CSUProjects/static/src/img/compProjects/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_preview',
            field=models.ImageField(blank=True, help_text='Изображение проекта (необязательно)', upload_to='CSUProjects/static/src/img/projects/'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='worker_photo',
            field=models.ImageField(upload_to='CSUProjects/static/src/img/compProjects/workers/'),
        ),
    ]
