# Generated by Django 4.2.6 on 2024-01-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0003_create_subprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(help_text='Требуемые профили обучения', max_length=80, verbose_name='Специальность')),
                ('description', models.TextField(help_text='Краткое описание требований', max_length=255, verbose_name='Требование к работнику')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects', verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': ('Вакансия',),
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
