# Generated by Django 4.2.6 on 2024-01-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0004_create_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersInSubprojects',
            fields=[
                ('wsid', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=80, verbose_name='Должность')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('sid', models.ForeignKey(help_text='Необходимо указать к какому проекту принадлежит', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.projects', verbose_name='Название проекта')),
                ('wid', models.ForeignKey(help_text='Необходимо указать кто участвует в проекте', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.workers', verbose_name='Имя участника')),
            ],
            options={
                'verbose_name': 'Исполнитель в подпроекте',
                'verbose_name_plural': 'Исполнители в подроектах',
            },
        ),
    ]
