# Generated by Django 4.2.6 on 2024-02-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSUProjects', '0005_create_workers_in_subprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workersinsubprojects',
            options={'verbose_name': 'Исполнитель в подпроекте', 'verbose_name_plural': 'Исполнители в подпроектах'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнен'), ('quickly', 'Срочно'), ('full', 'Набор окончен'), ('process', 'В процессе'), ('frozen', 'Заморожен')], default='process', help_text='Выберите состояние (статус) проекта', max_length=14, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='description',
            field=models.TextField(help_text='Краткое описание подпроекта', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subprojects',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнен'), ('quickly', 'Срочно'), ('full', 'Набор окончен'), ('process', 'В процессе'), ('frozen', 'Заморожен')], default='process', help_text='Выберите состояние (статус) подпроекта', max_length=14, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects', verbose_name='Название подпроекта'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='peoples/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workersinsubprojects',
            name='sid',
            field=models.ForeignKey(help_text='Необходимо указать к какому подпроекту принадлежит', on_delete=django.db.models.deletion.CASCADE, to='CSUProjects.subprojects', verbose_name='Название подпроекта'),
        ),
    ]
